import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { EmailMessage } from "./generate";

// On-brand: deep green + gold.
const INK = "#19211D";
const BRAND = "#123C3A";
const MUTED = "#65706C";
const LINE = "#DED9CF";

const s = StyleSheet.create({
  page: { paddingHorizontal: 44, paddingVertical: 40, fontSize: 11, color: INK, fontFamily: "Helvetica" },
  title: { fontSize: 22, fontFamily: "Helvetica-Bold", color: BRAND },
  sub: { color: MUTED, fontSize: 9, marginTop: 4, marginBottom: 22 },
  card: { borderWidth: 1, borderColor: LINE, borderRadius: 6, marginBottom: 14 },
  head: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 8, paddingHorizontal: 14, backgroundColor: "#F3F0E8", borderBottomWidth: 1, borderBottomColor: LINE },
  step: { fontFamily: "Helvetica-Bold", color: BRAND, fontSize: 10 },
  day: { color: MUTED, fontSize: 9 },
  subject: { paddingHorizontal: 14, paddingTop: 10, fontFamily: "Helvetica-Bold", fontSize: 11 },
  body: { paddingHorizontal: 14, paddingVertical: 10, lineHeight: 1.5, color: "#2A322E" },
  footer: { position: "absolute", bottom: 28, left: 44, right: 44, borderTopWidth: 1, borderTopColor: LINE, paddingTop: 8, textAlign: "center", color: MUTED, fontSize: 9 },
});

export function ColdEmailDocument({
  sequence,
  prospectCompany,
}: {
  sequence: EmailMessage[];
  prospectCompany: string;
}) {
  return (
    <Document title="Cold Email Sequence" author="Sampeer Studio">
      <Page size="A4" style={s.page}>
        <Text style={s.title}>Cold Email Sequence</Text>
        <Text style={s.sub}>
          {prospectCompany || "Prospect"} · {sequence.length} touches ·{" "}
          {new Date().toISOString().slice(0, 10)}
        </Text>

        {sequence.map((m) => (
          <View key={m.step} style={s.card} wrap={false}>
            <View style={s.head}>
              <Text style={s.step}>
                {m.step}. {m.label}
              </Text>
              <Text style={s.day}>Send day {m.day}</Text>
            </View>
            <Text style={s.subject}>Subject: {m.subject}</Text>
            <Text style={s.body}>{m.body}</Text>
          </View>
        ))}

        <View style={s.footer} fixed>
          <Text>Sampeer Studio · Generated by Sampeer Automations</Text>
        </View>
      </Page>
    </Document>
  );
}
