import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { formatMoney, type TaxInput, type TaxResult } from "./calc";

// On-brand: deep green + gold.
const INK = "#19211D";
const BRAND = "#123C3A";
const MUTED = "#65706C";
const LINE = "#DED9CF";

const s = StyleSheet.create({
  page: { paddingHorizontal: 44, paddingVertical: 40, fontSize: 11, color: INK, fontFamily: "Helvetica" },
  title: { fontSize: 22, fontFamily: "Helvetica-Bold", color: BRAND },
  sub: { color: MUTED, fontSize: 9, marginTop: 4, marginBottom: 24 },
  card: { borderWidth: 1, borderColor: LINE, borderRadius: 6, overflow: "hidden" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 9, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: LINE },
  label: { color: MUTED },
  grand: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 11, paddingHorizontal: 14, backgroundColor: BRAND },
  grandText: { color: "#FFFFFF", fontFamily: "Helvetica-Bold", fontSize: 13 },
  footer: { position: "absolute", bottom: 28, left: 44, right: 44, borderTopWidth: 1, borderTopColor: LINE, paddingTop: 8, textAlign: "center", color: MUTED, fontSize: 9 },
});

export function GstDocument({
  input,
  result,
}: {
  input: TaxInput;
  result: TaxResult;
}) {
  const money = (n: number) => formatMoney(n, input.currency);
  const name = input.taxName || "Tax";

  return (
    <Document title={`${name} Calculation`} author="Sampeer Studio">
      <Page size="A4" style={s.page}>
        <Text style={s.title}>{name} Calculation</Text>
        <Text style={s.sub}>
          {result.rate}% · {input.mode === "inclusive" ? "Tax inclusive" : "Tax exclusive"} ·{" "}
          {new Date().toISOString().slice(0, 10)}
        </Text>

        <View style={s.card}>
          <View style={s.row}>
            <Text style={s.label}>Base amount</Text>
            <Text>{money(result.base)}</Text>
          </View>
          {result.cgst > 0 || result.sgst > 0 ? (
            <>
              <View style={s.row}>
                <Text style={s.label}>CGST ({result.rate / 2}%)</Text>
                <Text>{money(result.cgst)}</Text>
              </View>
              <View style={s.row}>
                <Text style={s.label}>SGST ({result.rate / 2}%)</Text>
                <Text>{money(result.sgst)}</Text>
              </View>
            </>
          ) : result.igst > 0 ? (
            <View style={s.row}>
              <Text style={s.label}>IGST ({result.rate}%)</Text>
              <Text>{money(result.igst)}</Text>
            </View>
          ) : (
            <View style={s.row}>
              <Text style={s.label}>{name} ({result.rate}%)</Text>
              <Text>{money(result.taxAmount)}</Text>
            </View>
          )}
          <View style={s.grand}>
            <Text style={s.grandText}>Total</Text>
            <Text style={s.grandText}>{money(result.total)}</Text>
          </View>
        </View>

        <View style={s.footer} fixed>
          <Text>Sampeer Studio · Generated by Sampeer Automations</Text>
        </View>
      </Page>
    </Document>
  );
}
