import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { blended, channelMetrics, type ChannelRow } from "./calc";

const INK = "#19211D";
const BRAND = "#123C3A";
const MUTED = "#65706C";
const LINE = "#DED9CF";

const s = StyleSheet.create({
  page: { paddingHorizontal: 44, paddingVertical: 40, fontSize: 10, color: INK, fontFamily: "Helvetica" },
  title: { fontSize: 22, fontFamily: "Helvetica-Bold", color: BRAND },
  sub: { color: MUTED, fontSize: 9, marginTop: 4, marginBottom: 22 },
  th: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: BRAND, paddingBottom: 5 },
  tr: { flexDirection: "row", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: LINE },
  cName: { flex: 2 },
  c: { flex: 1, textAlign: "right" },
  thText: { fontFamily: "Helvetica-Bold", color: BRAND, fontSize: 9 },
  muted: { color: MUTED },
  grand: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 11, paddingHorizontal: 14, backgroundColor: BRAND, borderRadius: 6, marginTop: 18 },
  grandText: { color: "#FFFFFF", fontFamily: "Helvetica-Bold", fontSize: 13 },
  footer: { position: "absolute", bottom: 28, left: 44, right: 44, borderTopWidth: 1, borderTopColor: LINE, paddingTop: 8, textAlign: "center", color: MUTED, fontSize: 9 },
});

export function AnalyticsDocument({
  rows,
  currency,
}: {
  rows: ChannelRow[];
  currency: string;
}) {
  const b = blended(rows);
  const money = (n: number) => fmt(n, currency);

  return (
    <Document title="Growth Analytics" author="Sampeer Studio">
      <Page size="A4" style={s.page}>
        <Text style={s.title}>Growth Analytics</Text>
        <Text style={s.sub}>
          {rows.length} channels · {new Date().toISOString().slice(0, 10)}
        </Text>

        <View style={s.th}>
          <Text style={[s.cName, s.thText]}>Channel</Text>
          <Text style={[s.c, s.thText]}>Spend</Text>
          <Text style={[s.c, s.thText]}>CAC</Text>
          <Text style={[s.c, s.thText]}>Conv%</Text>
          <Text style={[s.c, s.thText]}>ROAS</Text>
          <Text style={[s.c, s.thText]}>Profit</Text>
        </View>
        {rows.map((r) => {
          const m = channelMetrics(r);
          return (
            <View key={r.id} style={s.tr}>
              <Text style={s.cName}>{r.channel || "Untitled"}</Text>
              <Text style={s.c}>{money(r.spend)}</Text>
              <Text style={s.c}>{money(m.cac)}</Text>
              <Text style={s.c}>{m.conversion}%</Text>
              <Text style={s.c}>{m.roas}x</Text>
              <Text style={s.c}>{money(m.profit)}</Text>
            </View>
          );
        })}

        <View style={s.grand}>
          <Text style={s.grandText}>Blended ROAS {b.roas}x</Text>
          <Text style={s.grandText}>Profit {money(b.profit)}</Text>
        </View>

        <View style={s.footer} fixed>
          <Text>Sampeer Studio · Generated by Sampeer Automations</Text>
        </View>
      </Page>
    </Document>
  );
}

function fmt(amount: number, currency: string): string {
  try {
    return new Intl.NumberFormat("en-US", { style: "currency", currency, minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount);
  } catch {
    return `${currency} ${Math.round(amount).toLocaleString("en-US")}`;
  }
}
