import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";
import type { ExpenseReport } from "./schema.js";
import { formatMoney } from "./calc.js";

// Brand palette - Sampeer Studio (born on-brand: deep green + gold).
const INK = "#19211D";
const BRAND = "#123C3A"; // deep green
const DEFAULT_ACCENT = "#B88A44"; // gold
const MUTED = "#65706C";
const LINE = "#DED9CF";
const WASH = "#EAF4F1";

function makeStyles(accent: string) {
  return StyleSheet.create({
    page: {
      paddingHorizontal: 44,
      paddingVertical: 40,
      fontSize: 10,
      color: INK,
      fontFamily: "Helvetica",
    },
    header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
    logo: { width: 90, height: 40, objectFit: "contain" },
    companyName: { fontSize: 16, fontFamily: "Helvetica-Bold", color: BRAND },
    title: { fontSize: 24, fontFamily: "Helvetica-Bold", color: BRAND, textAlign: "right" },
    metaLabel: { color: MUTED, fontSize: 8, textTransform: "uppercase", letterSpacing: 1 },
    metaValue: { fontSize: 10, marginBottom: 6 },
    small: { color: MUTED, fontSize: 9, lineHeight: 1.5 },
    sectionTitle: {
      fontSize: 8,
      fontFamily: "Helvetica-Bold",
      color: MUTED,
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 6,
    },
    headline: { fontSize: 12, color: BRAND, fontFamily: "Helvetica-Bold", marginBottom: 18, lineHeight: 1.4 },
    // Summary band
    summary: { flexDirection: "row", marginBottom: 24, borderRadius: 6, overflow: "hidden", borderWidth: 1, borderColor: LINE },
    sumCell: { width: "25%", paddingVertical: 12, paddingHorizontal: 12, borderRightWidth: 1, borderRightColor: LINE },
    sumValue: { fontSize: 13, fontFamily: "Helvetica-Bold", color: BRAND },
    sumLabel: { fontSize: 7.5, color: MUTED, textTransform: "uppercase", letterSpacing: 1, marginTop: 3 },
    // Tables
    tHead: {
      flexDirection: "row",
      backgroundColor: BRAND,
      color: "#FFFFFF",
      paddingVertical: 7,
      paddingHorizontal: 8,
      borderRadius: 4,
    },
    tRow: {
      flexDirection: "row",
      paddingVertical: 7,
      paddingHorizontal: 8,
      borderBottomWidth: 1,
      borderBottomColor: LINE,
    },
    th: { color: "#FFFFFF", fontSize: 9, fontFamily: "Helvetica-Bold" },
    cCat: { width: "46%" },
    cPct: { width: "18%", textAlign: "right" },
    cCount: { width: "16%", textAlign: "right" },
    cAmt: { width: "20%", textAlign: "right" },
    bar: { height: 5, backgroundColor: accent, borderRadius: 3, marginTop: 4 },
    block: { marginTop: 22 },
    insight: { flexDirection: "row", marginBottom: 4 },
    bullet: { color: accent, marginRight: 6, fontFamily: "Helvetica-Bold" },
    footer: {
      position: "absolute",
      bottom: 28,
      left: 44,
      right: 44,
      borderTopWidth: 1,
      borderTopColor: LINE,
      paddingTop: 8,
      textAlign: "center",
    },
  });
}

export function ExpenseDocument({ report }: { report: ExpenseReport }) {
  const cur = report.report.currency;
  const money = (n: number) => formatMoney(n, cur);
  const accent = report.branding?.accentColor || DEFAULT_ACCENT;
  const s = makeStyles(accent);
  const signature = report.branding?.emailSignatureName || "Sampeer Studio";
  const footerText = report.branding?.invoiceFooter || "Generated by Sampeer Automations";
  const maxCat = report.byCategory[0]?.total || 1;

  return (
    <Document title={`Expense Report - ${report.report.name}`} author={signature}>
      <Page size="A4" style={s.page}>
        {/* Header */}
        <View style={s.header}>
          <View>
            {report.branding?.logoUrl ? (
              <Image src={report.branding.logoUrl} style={s.logo} />
            ) : (
              <Text style={s.companyName}>{signature}</Text>
            )}
            <Text style={[s.small, { marginTop: 6 }]}>Expense Report</Text>
          </View>
          <View style={{ width: "50%", alignItems: "flex-end" }}>
            <Text style={s.title}>EXPENSES</Text>
            <Text style={[s.metaValue, { marginTop: 8 }]}>{report.report.name}</Text>
            <Text style={s.metaLabel}>
              {report.report.periodStart} - {report.report.periodEnd}
            </Text>
          </View>
        </View>

        {report.headline ? <Text style={s.headline}>{report.headline}</Text> : null}

        {/* Summary band */}
        <View style={s.summary}>
          <View style={s.sumCell}>
            <Text style={s.sumValue}>{money(report.summary.totalSpend)}</Text>
            <Text style={s.sumLabel}>Total Spend</Text>
          </View>
          <View style={s.sumCell}>
            <Text style={s.sumValue}>{money(report.summary.totalIncome)}</Text>
            <Text style={s.sumLabel}>Total Income</Text>
          </View>
          <View style={s.sumCell}>
            <Text style={s.sumValue}>{money(report.summary.net)}</Text>
            <Text style={s.sumLabel}>Net</Text>
          </View>
          <View style={[s.sumCell, { borderRightWidth: 0 }]}>
            <Text style={s.sumValue}>{money(report.summary.monthlyBurn)}</Text>
            <Text style={s.sumLabel}>Monthly Burn</Text>
          </View>
        </View>

        {/* Category breakdown */}
        <Text style={s.sectionTitle}>Spend by Category</Text>
        <View style={s.tHead}>
          <Text style={[s.th, s.cCat]}>Category</Text>
          <Text style={[s.th, s.cCount]}>Txns</Text>
          <Text style={[s.th, s.cPct]}>Share</Text>
          <Text style={[s.th, s.cAmt]}>Amount</Text>
        </View>
        {report.byCategory.map((c, i) => (
          <View key={i} style={s.tRow}>
            <View style={s.cCat}>
              <Text>{c.category}</Text>
              <View style={[s.bar, { width: `${Math.max(4, (c.total / maxCat) * 100)}%` }]} />
            </View>
            <Text style={s.cCount}>{c.count}</Text>
            <Text style={s.cPct}>{c.pct}%</Text>
            <Text style={s.cAmt}>{money(c.total)}</Text>
          </View>
        ))}

        {/* Top merchants */}
        {report.topMerchants.length ? (
          <View style={s.block}>
            <Text style={s.sectionTitle}>Top Merchants</Text>
            {report.topMerchants.map((m, i) => (
              <View key={i} style={{ flexDirection: "row", justifyContent: "space-between", paddingVertical: 2 }}>
                <Text style={{ width: "70%" }}>{m.merchant}</Text>
                <Text style={{ width: "30%", textAlign: "right" }}>{money(m.total)}</Text>
              </View>
            ))}
          </View>
        ) : null}

        {/* Insights */}
        {report.insights.length ? (
          <View style={s.block}>
            <Text style={s.sectionTitle}>Insights</Text>
            {report.insights.map((t, i) => (
              <View key={i} style={s.insight}>
                <Text style={s.bullet}>•</Text>
                <Text style={[s.small, { flex: 1 }]}>{t}</Text>
              </View>
            ))}
          </View>
        ) : null}

        {/* Footer */}
        <View style={s.footer} fixed>
          <Text style={s.small}>
            {signature} / {report.summary.txnCount} transactions / {footerText}
          </Text>
        </View>
      </Page>
    </Document>
  );
}
